from os import path as os_path
from APPETITE.Constants import DEFAULT_FIXING_DIAGNOSER as DEFAULT_TESTING_DIAGNOSER

MINIMUM_ORIGINAL_ACCURACY = 0.75
MINIMUM_DRIFT_ACCURACY_DROP = 0.1

# Transform the diagnoser to iterable
try:
    iter(DEFAULT_TESTING_DIAGNOSER)
    if isinstance(DEFAULT_TESTING_DIAGNOSER, str):
        raise TypeError
except TypeError:
    DEFAULT_TESTING_DIAGNOSER = (DEFAULT_TESTING_DIAGNOSER, )

SINGLE_DRIFT_TYPE = "single_drift"
PAIR_DRIFT_TYPE = "pair_drift"
MULTIPLE_DRIFT_TYPE = "multiple_drift"
SUPPORTED_DRIFT_TYPES = (SINGLE_DRIFT_TYPE, PAIR_DRIFT_TYPE)
CURRENT_DRIFT_TYPE = PAIR_DRIFT_TYPE


STOP_ON_EXCEPTION = False

WASTED_EFFORT_REQUIRE_FULL_FIX = True # Fix all faulty features

DATA_DIRECTORY = "data"
DATASET_DESCRIPTION_FILE_NAME = "all_datasets"
DATASET_DESCRIPTION_FILE_PATH = os_path.join(DATA_DIRECTORY, f"{DATASET_DESCRIPTION_FILE_NAME}.csv")
DATASETS_DIRECTORY = "Classification_Datasets"
DATASETS_FULL_PATH = os_path.join(DATA_DIRECTORY, DATASETS_DIRECTORY)

RESULTS_DIRECTORY = "results"
RESULTS_FULL_PATH = os_path.join(DATA_DIRECTORY, RESULTS_DIRECTORY)
TEMP_RESULTS_DIRECTORY = "temp"
TEMP_RESULTS_FULL_PATH = os_path.join(RESULTS_FULL_PATH, TEMP_RESULTS_DIRECTORY)
RESULTS_FILE_NAME_PREFIX = "results"
ERRORS_FILE_NAME_PREFIX = "errors"

EXAMPLE_FILE_NAME = "bank"