MINIMUM_ORIGINAL_ACCURACY = 0.75
MINIMUM_DRIFT_ACCURACY_DROP = 0.1

DEFAULT_TESTING_DIAGNOSER = ("BARINEL_Combo")

WRAP_EXCEPTION = True

WASTED_EFFORT_REQUIRE_FULL_FIX = True # Fix all faulty features