MINIMUM_ORIGINAL_ACCURACY = 0.75
MINIMUM_DRIFT_ACCURACY_DROP = 0.1

DEFAULT_TESTING_DIAGNOSER = ("BARINEL_Paths_After", "BARINEL_Paths_Difference")

# Transform the diagnoser to iterable
try:
    iter(DEFAULT_TESTING_DIAGNOSER)
except TypeError:
    DEFAULT_TESTING_DIAGNOSER = (DEFAULT_TESTING_DIAGNOSER,)

SINGLE_DRIFT_TYPE = "single_drift"
MULTIPLE_DRIFT_TYPE = "multiple_drift"
SUPPORTED_DRIFT_TYPES = (SINGLE_DRIFT_TYPE)
CURRENT_DRIFT_TYPE = SINGLE_DRIFT_TYPE


STOP_ON_EXCEPTION = False

WASTED_EFFORT_REQUIRE_FULL_FIX = True # Fix all faulty features

DATA_DIRECTORY = "data"
DATASET_DESCRIPTION_FILE_NAME = "all_datasets"
DATASET_DESCRIPTION_FILE_PATH = f"{DATA_DIRECTORY}\\{DATASET_DESCRIPTION_FILE_NAME}.csv"
DATASETS_DIRECTORY = "Classification_Datasets"
DATASETS_FULL_PATH = f"{DATA_DIRECTORY}\\{DATASETS_DIRECTORY}\\"

RESULTS_DIRECTORY = "results"
RESULTS_FULL_PATH = f"{DATA_DIRECTORY}\\{RESULTS_DIRECTORY}\\"
RESULTS_FILE_NAME_PREFIX = "results"
ERRORS_FILE_NAME_PREFIX = "errors"
RESULTS_FILE_PATH_PREFIX = f"{RESULTS_FULL_PATH}{RESULTS_FILE_NAME_PREFIX}"
ERRORS_FILE_PATH_PREFIX = f"{RESULTS_FULL_PATH}{ERRORS_FILE_NAME_PREFIX}"

EXAMPLE_FILE_NAME = "bank"